name: Run type check

on:
  push:
    branches-ignore: [sync, stable]
    paths: ["colors/**", "lua/**", "tests/**"]
  pull_request:
    branches-ignore: [sync, stable]
    paths: ["colors/**", "lua/**", "tests/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    name: Run tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Install lua-language-server
        uses: jdx/mise-action@v2
        with:
          tool_versions: |
            lua-language-server 3.15.0

      - name: Run tests
        run:
          export VIMRUNTIME="/home/runner/nvim-stable/runtime"

          echo VIMRUNTIME
          
          ls VIMRUNTIME

          make types
